import "./globals.css";
import Navbar from "./Components/Navbar";
import Marque from "./Components/Marque";
import Footer from "./Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Marque />
        {children}
        <Footer />
      </body>
    </html>
  );
}
